export namespace Flag {
  export const OPENSPLOIT_AUTO_SHARE = truthy("OPENSPLOIT_AUTO_SHARE", "OPENCODE_AUTO_SHARE")
  export const OPENSPLOIT_GIT_BASH_PATH = env("OPENSPLOIT_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH")
  export const OPENSPLOIT_CONFIG = env("OPENSPLOIT_CONFIG", "OPENCODE_CONFIG")
  export const OPENSPLOIT_CONFIG_DIR = env("OPENSPLOIT_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  export const OPENSPLOIT_CONFIG_CONTENT = env("OPENSPLOIT_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT")
  export const OPENSPLOIT_DISABLE_AUTOUPDATE = truthy("OPENSPLOIT_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE")
  export const OPENSPLOIT_DISABLE_PRUNE = truthy("OPENSPLOIT_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE")
  export const OPENSPLOIT_DISABLE_TERMINAL_TITLE = truthy("OPENSPLOIT_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE")
  export const OPENSPLOIT_PERMISSION = env("OPENSPLOIT_PERMISSION", "OPENCODE_PERMISSION")
  export const OPENSPLOIT_DISABLE_DEFAULT_PLUGINS = truthy("OPENSPLOIT_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const OPENSPLOIT_DISABLE_LSP_DOWNLOAD = truthy("OPENSPLOIT_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const OPENSPLOIT_ENABLE_EXPERIMENTAL_MODELS = truthy("OPENSPLOIT_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENSPLOIT_DISABLE_AUTOCOMPACT = truthy("OPENSPLOIT_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT")
  export const OPENSPLOIT_DISABLE_MODELS_FETCH = truthy("OPENSPLOIT_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH")
  export const OPENSPLOIT_FAKE_VCS = env("OPENSPLOIT_FAKE_VCS", "OPENCODE_FAKE_VCS")
  export const OPENSPLOIT_CLIENT = env("OPENSPLOIT_CLIENT", "OPENCODE_CLIENT") ?? "cli"

  // Experimental
  export const OPENSPLOIT_EXPERIMENTAL = truthy("OPENSPLOIT_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
  export const OPENSPLOIT_EXPERIMENTAL_FILEWATCHER = truthy("OPENSPLOIT_EXPERIMENTAL_FILEWATCHER", "OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const OPENSPLOIT_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("OPENSPLOIT_EXPERIMENTAL_DISABLE_FILEWATCHER", "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENSPLOIT_EXPERIMENTAL_ICON_DISCOVERY =
    OPENSPLOIT_EXPERIMENTAL || truthy("OPENSPLOIT_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const OPENSPLOIT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("OPENSPLOIT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENSPLOIT_ENABLE_EXA =
    truthy("OPENSPLOIT_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || OPENSPLOIT_EXPERIMENTAL || truthy("OPENSPLOIT_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA")
  export const OPENSPLOIT_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("OPENSPLOIT_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH", "OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const OPENSPLOIT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("OPENSPLOIT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENSPLOIT_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("OPENSPLOIT_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENSPLOIT_EXPERIMENTAL_OXFMT = OPENSPLOIT_EXPERIMENTAL || truthy("OPENSPLOIT_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT")
  export const OPENSPLOIT_EXPERIMENTAL_LSP_TY = truthy("OPENSPLOIT_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY")
  export const OPENSPLOIT_EXPERIMENTAL_LSP_TOOL = OPENSPLOIT_EXPERIMENTAL || truthy("OPENSPLOIT_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL")

  function env(primary: string, fallback: string): string | undefined {
    return process.env[primary] ?? process.env[fallback]
  }

  function truthy(primary: string, fallback: string) {
    const value = (process.env[primary] ?? process.env[fallback])?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(primary: string, fallback: string) {
    const value = process.env[primary] ?? process.env[fallback]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
